# MERGE005
Best of Each Type as of July 3

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error

def group_mean_log_mae(y_true, y_pred, groups, floor=1e-9):
    maes = (y_true-y_pred).abs().groupby(groups).mean()
    return np.log(maes.map(lambda x: max(x, floor))).mean()

In [2]:
tracking = pd.read_csv('../tracking/tracking.csv')

In [3]:
tracking.head()

      run_id model_number eval_metric  n_estimators  early_stopping_rounds  random_state        ...         2JHN_tr_sec_f3  2JHN_pred_sec_f3  3JHH_tr_sec_f3 3JHH_pred_sec_f3  2JHC_tr_sec_f3  2JHC_pred_sec_f3
0  0610_1341         M010         mae      500000.0                  500.0         529.0        ...                    NaN               NaN             NaN              NaN             NaN               NaN
1  0611_0308         M012         mae      500000.0                  500.0         529.0        ...                    NaN               NaN             NaN              NaN             NaN               NaN
2  0611_1250         M013         mae       50000.0                  500.0         529.0        ...                    NaN               NaN             NaN              NaN             NaN               NaN
3  0611_1249         M014         mae      500000.0                  500.0         529.0        ...                    NaN               NaN             NaN              NaN             NaN               NaN
4  0613_0402         M015         mae      500000.0                  500.0         529.0        ...                    NaN               NaN             NaN              NaN             NaN               NaN

[5 rows x 84 columns]

In [26]:
tracking[['model_number','run_id','model_type',
          '1JHC_mae_cv', '2JHH_mae_cv', '1JHN_mae_cv',
          '2JHN_mae_cv', '2JHC_mae_cv', '3JHH_mae_cv',
          '3JHC_mae_cv', '3JHN_mae_cv']].sort_values('2JHC_mae_cv').head()

   model_number     run_id model_type  1JHC_mae_cv  2JHH_mae_cv  1JHN_mae_cv  2JHN_mae_cv  2JHC_mae_cv  3JHH_mae_cv  3JHC_mae_cv  3JHN_mae_cv
24         M032  0703_2133   catboost       0.6068       0.1615       0.4427       0.1406       0.2866       0.1990          NaN          NaN
13         M025  0629_1311   catboost       0.6691       0.1640       0.4348       0.1398       0.3002       0.1934       0.3905       0.1627
16         M027  0629_2221   catboost       0.6594       0.1763       0.4457       0.1522       0.3143       0.2135       0.4148       0.1786
17         M028  0630_1258   catboost       0.6569       0.1765       0.5243       0.1512       0.3145       0.2143       0.4156       0.1782
12         M024  0627_1434       lgbm       0.7073       0.1739       0.3909       0.1478       0.3198       0.2082       0.4221       0.1750

In [23]:
# 1JHC - M031
# 2JHH - M031
# 1JHN - M030
# 2JHN - M031
# 2JHC - M032
# 3JHH - M025
# 3JHC - M025
# 3JHN - M025

sub_M031 = pd.read_csv('../temp/temp4of8_M031_0702_0822_submission_lgb_3folds_5000000iter_0.05lr.csv')
oof_M031 = pd.read_csv('../temp/temp4of8_M031_0702_0822_oof_lgb_3folds_5000000iter_0.05lr.csv')

In [17]:
sub_M032 = pd.read_csv('../temp/temp6of8_M032_0703_2133_submission_lgb_3folds_5000000iter_0.1lr.csv')
oof_M032 = pd.read_csv('../temp/temp6of8_M032_0703_2133_oof_lgb_3folds_5000000iter_0.1lr.csv')

In [19]:
sub_M030_a = pd.read_csv('../temp/temp4of8_M030_0701_1300_submission_lgb_3folds_5000000iter_0.05lr.csv')
sub_M030_b = pd.read_csv('../temp/temp4of8_M030_0701_1302_submission_lgb_3folds_5000000iter_0.05lr.csv')
sub_M030_c = pd.read_csv('../temp/temp4of8_M030_0701_1304_submission_lgb_3folds_5000000iter_0.05lr.csv')
sub_M030 = sub_M030_a.copy()
sub_M030['scc_a'] = sub_M030_a['scalar_coupling_constant']
sub_M030['scc_b'] = sub_M030_b['scalar_coupling_constant']
sub_M030['scc_c'] = sub_M030_c['scalar_coupling_constant']
sub_M030['scalar_coupling_constant'] = sub_M030[['scc_a','scc_b','scc_c']].mean(axis=1)
sub_M030 = sub_M030.drop(['scc_a','scc_b','scc_c'], axis=1).copy()

In [20]:
oof_M030_a = pd.read_csv('../temp/temp4of8_M030_0701_1300_oof_lgb_3folds_5000000iter_0.05lr.csv')
oof_M030_b = pd.read_csv('../temp/temp4of8_M030_0701_1302_oof_lgb_3folds_5000000iter_0.05lr.csv')
oof_M030_c = pd.read_csv('../temp/temp4of8_M030_0701_1304_oof_lgb_3folds_5000000iter_0.05lr.csv')
oof_M030 = oof_M030_a.copy()
oof_M030['scc_a'] = oof_M030_a['oof_preds']
oof_M030['scc_b'] = oof_M030_b['oof_preds']
oof_M030['scc_c'] = oof_M030_c['oof_preds']
oof_M030['oof_preds'] = oof_M030[['scc_a','scc_b','scc_c']].sum(axis=1)
oof_M030 = oof_M030.drop(['scc_a','scc_b','scc_c'], axis=1).copy()

In [21]:
sub_M025 = pd.read_csv('../submissions/M025_0629_1311_submission_lgb_2folds_-1.3265CV_500000iter_0.1lr.csv')
oof_M025 = pd.read_csv('../oof/M025_0629_1311_oof_lgb_2folds_-1.3265CV_500000iter_0.1lr.csv')

In [24]:
oof_final = oof_M031[['id','type','scalar_coupling_constant']].copy()
oof_final.loc[oof_final['type'].isin(['1JHC','2JHH','2JHN']), 'oof_preds'] = \
    oof_M031.loc[oof_final['type'].isin(['1JHC','2JHH','2JHN'])]['oof_preds']

oof_final.loc[oof_final['type'].isin(['1JHN']), 'oof_preds'] = \
    oof_M030.loc[oof_final['type'].isin(['1JHN'])]['oof_preds']

oof_final.loc[oof_final['type'].isin(['3JHH','3JHC','3JHN']), 'oof_preds'] = \
    oof_M025.loc[oof_final['type'].isin(['3JHH','3JHC','3JHN'])]['oof_preds']

oof_final.loc[oof_final['type'].isin(['2JHC']), 'oof_preds'] = \
    oof_M032.loc[oof_final['type'].isin(['2JHC'])]['oof_preds']

In [27]:
for i, d in oof_final.groupby('type'):
    print(i)
    print(mean_absolute_error(d['scalar_coupling_constant'], d['oof_preds']))

1JHC
0.5792659784491359
1JHN
0.35815790678334736
2JHC
0.2866363023454614
2JHH
0.15434779537534812
2JHN
0.13000911360249118
3JHC
0.39051763625418157
3JHH
0.1934145785886842
3JHN
0.1627272677520273

In [28]:
group_mean_log_mae(oof_final['scalar_coupling_constant'], oof_final['oof_preds'], oof_final['type'])

-1.3912368292340955

In [29]:
test = pd.read_csv('../input/test.csv')

In [30]:
test.loc[test['type'].isin(['1JHC','2JHH','2JHN']), 'scalar_coupling_constant'] = \
    sub_M031.loc[test['type'].isin(['1JHC','2JHH','2JHN'])]['scalar_coupling_constant']

test.loc[test['type'].isin(['1JHN']), 'scalar_coupling_constant'] = \
    sub_M030.loc[test['type'].isin(['1JHN'])]['scalar_coupling_constant']

test.loc[test['type'].isin(['3JHH','3JHC','3JHN']), 'scalar_coupling_constant'] = \
    sub_M025.loc[test['type'].isin(['3JHH','3JHC','3JHN'])]['scalar_coupling_constant']

test.loc[test['type'].isin(['2JHC']), 'scalar_coupling_constant'] = \
    sub_M032.loc[test['type'].isin(['2JHC'])]['scalar_coupling_constant']

In [31]:
test['scc_good'] = sub_M025['scalar_coupling_constant']

In [32]:
test[['scc_good','scalar_coupling_constant']].corr()

                          scc_good  scalar_coupling_constant
scc_good                  1.000000                  0.999976
scalar_coupling_constant  0.999976                  1.000000

In [33]:
sub_M025.head()

        id  scalar_coupling_constant
0  4658147                  8.873624
1  4658148                134.914493
2  4658149                  3.716820
3  4658150                134.914493
4  4658151                  8.873624

In [34]:
test[['id','scalar_coupling_constant']].to_csv('../submissions/MERGE006-M025-M031-M030-M032_-1.3912CV.csv', index=False)